ms_employee:
  build: ./employee/
  container_name: ms_employee
  restart: unless-stopped
  ports:
    - "8081:8080"
    - "8000:8000"

ms_shipment:
  build: ./shipment/
  container_name: ms_shipment
  restart: unless-stopped
  ports:
    - "8082:8080"
    - "8001:8001"

