configserver:
  extends:
    file: docker-compose-common.yml
    service: configserver

ms_employee:
  extends:
    file: docker-compose-common.yml
    service: ms_employee
  links:
    - db_mongodb-employee

ms_shipment:
  extends:
    file: docker-compose-common.yml
    service: ms_shipment
  links:
    - db_mongodb-shipment

db_mongodb-employee:
  image: mongo
  container_name: db_mongodb-employee
  ports:
    - "27017"

db_mongodb-shipment:
  image: mongo
  container_name: db_mongodb-shipment
  ports:
    - "27017"