ms_employee:
  extends:
    file: docker-compose-common.yml
    service: ms_employee
  links:
    - db_mongodb-employee
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://db_mongodb-employee/micros

shipment:
  extends:
    file: docker-compose-common.yml
    service: ms_shipment
  links:
    - db_mongodb-shipment
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://db_mongodb-shipment/micros

db_mongodb-employee:
  image: mongo
  container_name: db_mongodb-employee
  ports:
    - 27017:27017

db_mongodb-shipment:
  image: mongo
  container_name: db_mongodb-shipment
  ports:
    - 27018:27017