ms_employee:
  extends:
    file: docker-compose-common.yml
    service: ms_employee
  links:
    - db_mongodb-employee
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://db_mongodb-employee/micros
    JPDA_ADDRESS: 8000
    JPDA_TRANSPORT: dt_socket
    JVM_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -Djava.security.egd=file:/dev/./urandom

shipment:
  extends:
    file: docker-compose-common.yml
    service: ms_shipment
  links:
    - db_mongodb-shipment
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://db_mongodb-shipment/micros
    JPDA_ADDRESS: 8001
    JPDA_TRANSPORT: dt_socket
    JVM_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8001 -Djava.security.egd=file:/dev/./urandom

db_mongodb-employee:
  image: mongo
  container_name: db_mongodb-employee
  ports:
    - 27017:27017

db_mongodb-shipment:
  image: mongo
  container_name: db_mongodb-shipment
  ports:
    - 27018:27017