employee:
  build: ./employee/
  restart: unless-stopped
  ports:
    - "8081:8080"
    - "8000:8000"

shipment:
  build: ./shipment/
  restart: unless-stopped
  ports:
    - "8082:8080"
    - "8001:8001"

