configserver:
  build: ./configserver/
  container_name: configserver
  restart: unless-stopped
  ports:
    - "8888"
#  environment:
#    CFG_SRV_KEYPASS: changeme
#    CFG_SRV_STOREPASS: letmein

ms_employee:
  build: ./ms_employee/
  container_name: ms_employee
  restart: unless-stopped
  ports:
    - "8080"
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://db_mongodb-employee/micros

ms_shipment:
  build: ./ms_shipment/
  container_name: ms_shipment
  restart: unless-stopped
  ports:
    - "8080"
  environment:
    SPRING_DATA_MONGODB_URI: mongodb://db_mongodb-shipment/micros